server:
  port: ${CUSTOM.SERVER.PORT:9099}

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:  Ov23li284rzBlAXezmYo
            client-secret:  b5b6655de0b44a5a963d03bf18d4bdddf8ed0921
